---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Remove the Avi image file in the bucket
      gcp_storage_object:
        action: upload
        bucket: "{{ bucketAvi }}"
        src: gcp_controller.tar.gz
        dest: gcp_controller.tar.gz
        auth_kind: machineaccount
        state: absent
        service_account_email: "{{ googleEmail }}"
        overwrite: yes
        # it does not seem to work
