---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: Remove the Avi image file in the bucket
      google.cloud.gcp_storage_object:
        action: delete
        bucket: "{{ bucketAvi }}"
        auth_kind: machineaccount
        state: absent
        service_account_email: "{{ googleEmail }}"
